// Initial chemicals data
export const initialChemicals = [
  "Acetamide", "Acetic Acid", "Acetanilide", "Acetone", "Acetyl Salicylic Acid", "Activated Zinc metal Powder",
  "Agar Agar Powder", "Alizarine", "Aluminium Sulphate", "Ammonia", "Ammonium Chloride", "Ammonium Ferrous Sulfate",
  "Ammonium Hydroxide", "Ammonium Iron (II) Sulphate", "Ammonium Oxalate", "Ammonium Thiocyanate", "Aniline",
  "Barium Chloride", "Barium Hydroxide", "Benzaldehyde", "Benzamide", "Benzene", "Benzoic Acid", "Benzoinoxime",
  "Benzidine", "Bleaching Powder", "Brass Fillings", "Bromine water", "Buffer capsules", "Butan-2-one Extrapure",
  "Calcon Carboxylic Acid", "Calcium Carbonate", "Calcium Chloride", "Calcium Tetrachloride", "Carboxy Methyl Cellulose",
  "Cellulose Powder", "Cetylpyridinium bromide", "Charcoal Powder", "Cobalt Nitrate", "Cobaltous Chloride",
  "Copper filings", "Copper Sulphate", "Cyclohexanone", "Dextrose", "Diethyl Ether",
  "Dimethyl Glyoxime", "di-Sodium Phosphate", "Diphenylamine", "Dithiozone", "Dolomite Powder", "EDTA",
  "2,4-Dinitrophenol", "Ethyl Acetate", "Ethyl Alcohol", "Ethyl Benzoate",
  "Ethyl Cellulose", "Ethyl Methyl Ketone", "Ethylenediamine", "Ethanol", "Ether Solvent", "Fumaric Acid",
  "Formaldehyde", "Formalin", "Formic Acid", "Furfuraldehyde", "Furfuryl Alcohol", "Fehling Solution A",
  "Fehling Solution B", "Ferric Chloride", "Ferrous Sulphate", "Glacial Acetic Acid", "Glucose",
  "Glycerin", "Glycine", "Guar Gum", "Hexane", "Hydrochloric Acid", "Hydrogen Peroxide",
  "Hydroxyethyl Cellulose", "L-Alginine", "L-Cystine", "Iodine", "Iodine Crystal", "Iron Metal Powder",
  "Liquid Paraffin", "Lime Water", "Lead Acetate", "Lead Nitrate", "Methyl Cellulose", "n-Butyl Alcohol",
  "Magnesium Sulphate", "Ortho Phosphoric Acid", "2-Nitrophenol", "3-Nitro Aniline", "Oxalic Acid", "Nitrobenzene",
  "Methyl Acetate", "Nickel Chloride", "Mercuric Chloride", "Picric Acid", "Phthalic Acid", "1-Naphthol",
  "Methyl Orange", "Polyvinyl Alcohol", "Potassium Carbonate", "Potassium Dichromate", "p-Nitroaniline",
  "Methylene Blue", "Potassium Nitrate", "Ninhydrin", "Methanesulfonic Acid", "n-Butyl Acetate",
  "Phthalic Anhydride", "Potassium Chloride", "Methyl Alcohol", "Nitroso-R Salt", "Nickel Nitrate",
  "Methanol", "β-Naphthol", "α-Naphthol", "Naphthalene", "p-Nitrophenol",
  "Potassium Permanganate", "Potassium Persulfate", "Potassium Bromide", "Potassium Fluoride",
  "Potassium Thiocyanate", "Potassium Iodide", "Potassium Dithionite", "Nitric Acid", "Orthophosphate",
  "Nickel Acetate Hexahydrate", "Phosphoric Acid", "Nickel Sulphate", "Potassium Hydroxide",
  "Potassium Ferrocyanide", "Phenolphthalein Indicator", "Phenol", "Potassium Chromate", "p-Toluidine",
  "Petroleum Ether", "1,10-Phenanthroline Hydrate", "Potassium Carbonate Anhydrous", "Phenyl Hydrazine",
  "Hydroquinone", "Paraffin Wax Pure", "Rubeanic Acid", "Resorcinol", "Sodium Carbonate", "Sodium Nitrate",
  "Sodium Hydroxide Pellets", "Sodium Phosphate Dibasic", "Sodium Thiosulfate", "Semicarbazide Hydrochloride",
  "Sodium Potassium Tartrate", "Sodium Sulphate Anhydrous", "Sodium Azide", "Sodium Iodide", "Sodium Acetate",
  "Sodium Sulphate", "Sulphur Powder", "Sodium Bicarbonate", "Sodium Nitroprusside", "Schiff's Reagent",
  "Stannous Chloride", "Urease", "Sodium Sulphite Flakes", "Starch Indicator", "Silver Nitrate", "Sulfuric Acid",
  "Spirit", "Salicylic Acid", "Thiourea", "Tollens Reagent", "Urea", "Zinc Sulphate",
  "Zinc Chloride Powder", "Zinc Oxide Pure", "Zinc Dust"
];

// Initial equipment data
export const initialEquipment = [
  "Asbestos Sheet", "B.O.D. Bottle", "Burette 10mL", "Burette", "Burette Stand with Clip", "BOD Bottle",
  "Beaker 1000mL", "Beaker 500mL", "Beaker 250mL", "Beaker 100mL", "Beaker 25mL", "Buchner Funnel Small",
  "Buchner Funnel Big", "Capillary Tube", "Conical Flask 1000mL", "Conical Flask 500mL", "Conical Flask 250mL",
  "Conical Flask 100mL", "Crucible with Lid", "Congo Red Paper", "Cotton Bleached", "Dessicator",
  "Drop Bottle Glass", "Column Chromatography Flask", "Filter Flask 500mL", "Fire Bucket with Sand",
  "Evaporating Dish", "First Aid Box", "Funnel", "Filter Paper", "Funnel 100mL", "Filter Flask 100mL",
  "Glass Funnel Small", "Glass Column", "Gas Pipe", "Glass Rod", "Crucible", "ID Jar",
  "Landberger's Apparatus", "Iodine Flask Glass 2500mL", "Measuring Cylinder", "Notice Board",
  "Ostwald Viscometer", "Plastic Funnel Big", "Plastic Lid", "Measuring Cylinder Plastic 100mL",
  "Measuring Cylinder 10mL", "Measuring Cylinder 25mL", "Measuring Cylinder 50mL", "Measuring Cylinder 100mL",
  "Pipette 25mL", "Pipette 100mL", "Plastic Sample Bottle", "Pestle and Mortar", "Plastic Funnel Small",
  "Plastic Beaker 500mL", "Plastic Beaker 1L", "Pipe Clay Triangle", "Petri Dish", "Plastic Beaker 2500mL",
  "Plastic Beaker 250mL", "Plastic Water Bath", "Plastic Tray", "Rubber Cork", "Reagent Bottle",
  "Spatula Metal", "Test Tube Holder", "Reflux Condenser", "Spatula Plastic", "Test Tube Stand",
  "Rubber Tubing for Burette", "Steel Water Bath", "Thiele Tube", "Sodium Fusion Tube", "Scissors",
  "TLC Jar", "Round Bottom Flask 2 Neck", "Specific Gravity Bottle", "Test Tube Box",
  "Round Bottom Flask 100mL", "Thermometer 110°C", "Stalagmometer", "Thermometer 300°C",
  "Separating Funnel", "Test Tube Brush 6 inch", "Turmeric Paper", "Volumetric Flask 100mL",
  "Volumetric Flask 250mL", "Volumetric Flask 500mL", "Volumetric Flask 1000mL",
  "Volumetric Flask Plastic 1000mL", "Volumetric Flask Plastic 500mL", "Volumetric Flask Glass 100mL",
  "Viscometer 10mL", "Viscometer 25mL", "Wire Gauze", "White Can 5L", "Wash Bottle 500mL Plastic",
  "Whatman Filter Paper", "Watch Glass"
];
